


writer.write("<!DOCTYPE html>");
writer.write("<html>");
writer.write("  <head>");
writer.write("    <meta charset=\"UTF-8\">");
writer.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
writer.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
writer.write("    <link rel=\"stylesheet\" href=\"../Main.css\">");
writer.write("    <link rel=\"stylesheet\" href=\"../FontFolder/FontCSS.css\">");
writer.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">");
writer.write("    <link rel=icon type=image/x-icon href=../ImgFolder/Favicon.ico>");
writer.write("    <title>Företagskupan UF</title>");
writer.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>");
writer.write("  </head>");
writer.write("  <body class=\"body-main\">");
writer.write("    <!--Navbar-->");
writer.write("    <nav class=\"navbar navbar-expand-md navbar-dark navbarbg\">");
writer.write("      <div class=\"container-fluid\">");
writer.write("        <img src=\"../ImgFolder/LogoNoBackground.png\" alt=\"Avatar Logo\" style=\"width: 60px;\" class=\"navbar-brand\"> ");
writer.write("        <span class=\"navbar-brand fs-1\">Företagskupan UF</span>");
writer.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapsibleNavbar\">");
writer.write("          <span class=\"navbar-toggler-icon\"></span>");
writer.write("        </button>");
writer.write("        <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">");
writer.write("          <ul class=\"navbar-nav\">");
writer.write("            <li class=\"nav-item\">");
writer.write("              <a class=\"nav-link\" href=\"../default.html\">Startsida</a>");
writer.write("            </li>");
writer.write("            <li class=\"nav-item\">");
writer.write("              <a class=\"nav-link\" href=\"../foretagen.html\">Företagen</a>");
writer.write("            </li>");
writer.write("            <li class=\"nav-item\">");
writer.write("              <a class=\"nav-link\" href=\"../forforetag.html\">För UF Företag</a>");
writer.write("            </li>    ");
writer.write("            <li class=\"nav-item\">");
writer.write("              <a class=\"nav-link\" href=\"../omoss.html\">Om oss</a>");
writer.write("            </li> ");
writer.write("          </ul>");
writer.write("        </div>");
writer.write("      </div>");
writer.write("    </nav> ");
writer.write("    ");
writer.write("    <div class=\"row\" style=\"margin:1px\"> ");
writer.write("        <!--");
writer.write("        <div class=\"col-md-6 hex-img mx-5 mt-2\" id=\"foretag-beautybox\"></div>");
writer.write("        -->");
writer.write("        <img src=\"../ImgFolder/foretag_loggor/beautybox.jpg\" alt=\"Beautybox UF logo\" class=\"col-md-6 px-2 my-4 \">");
writer.write("");
writer.write("        <div class=\"my-3 col-md-5 offset-1px-2 pe-5 mt-md-5 col-xs-11\">");
writer.write("            <h1>Beautybox UF</h1>");
writer.write("            <h3>Skönhet</h3>");
writer.write("            <p class=\"fs-5\">Beauty Box UF säljer en beauty box med innehåll av sminkredskap & ett test av mineralsmink.</p>");
writer.write("");
writer.write("            <h3>Länkar</h3>");
writer.write("            <p class=\"fs-5\">Instagram: <a href=\"instagram.com\">beautybox</a></p>");
writer.write("        </div>");
writer.write("        ");
writer.write("    </div>");
writer.write("");
writer.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>");
writer.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js\" integrity=\"sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+\" crossorigin=\"anonymous\"></script>");
writer.write("");
writer.write("  </body>");
writer.write("</html>");
